// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: proto/project.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_proto_project_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_project_proto_rawDescGZIP(), []int{0}
}

type GetStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         []*CategoryStat        `protobuf:"bytes,1,rep,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	mi := &file_proto_project_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_project_proto_rawDescGZIP(), []int{1}
}

func (x *GetStatsResponse) GetStats() []*CategoryStat {
	if x != nil {
		return x.Stats
	}
	return nil
}

type CategoryStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	AverageApr    float32                `protobuf:"fixed32,3,opt,name=average_apr,json=averageApr,proto3" json:"average_apr,omitempty"`
	AverageIncome float32                `protobuf:"fixed32,4,opt,name=average_income,json=averageIncome,proto3" json:"average_income,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryStat) Reset() {
	*x = CategoryStat{}
	mi := &file_proto_project_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryStat) ProtoMessage() {}

func (x *CategoryStat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryStat.ProtoReflect.Descriptor instead.
func (*CategoryStat) Descriptor() ([]byte, []int) {
	return file_proto_project_proto_rawDescGZIP(), []int{2}
}

func (x *CategoryStat) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *CategoryStat) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CategoryStat) GetAverageApr() float32 {
	if x != nil {
		return x.AverageApr
	}
	return 0
}

func (x *CategoryStat) GetAverageIncome() float32 {
	if x != nil {
		return x.AverageIncome
	}
	return 0
}

type FetchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchRequest) Reset() {
	*x = FetchRequest{}
	mi := &file_proto_project_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchRequest) ProtoMessage() {}

func (x *FetchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchRequest.ProtoReflect.Descriptor instead.
func (*FetchRequest) Descriptor() ([]byte, []int) {
	return file_proto_project_proto_rawDescGZIP(), []int{3}
}

type FetchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchResponse) Reset() {
	*x = FetchResponse{}
	mi := &file_proto_project_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchResponse) ProtoMessage() {}

func (x *FetchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchResponse.ProtoReflect.Descriptor instead.
func (*FetchResponse) Descriptor() ([]byte, []int) {
	return file_proto_project_proto_rawDescGZIP(), []int{4}
}

func (x *FetchResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetAllDepositsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllDepositsRequest) Reset() {
	*x = GetAllDepositsRequest{}
	mi := &file_proto_project_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllDepositsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllDepositsRequest) ProtoMessage() {}

func (x *GetAllDepositsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllDepositsRequest.ProtoReflect.Descriptor instead.
func (*GetAllDepositsRequest) Descriptor() ([]byte, []int) {
	return file_proto_project_proto_rawDescGZIP(), []int{5}
}

type GetAllDepositsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deposits      []*Deposit             `protobuf:"bytes,1,rep,name=deposits,proto3" json:"deposits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllDepositsResponse) Reset() {
	*x = GetAllDepositsResponse{}
	mi := &file_proto_project_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllDepositsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllDepositsResponse) ProtoMessage() {}

func (x *GetAllDepositsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllDepositsResponse.ProtoReflect.Descriptor instead.
func (*GetAllDepositsResponse) Descriptor() ([]byte, []int) {
	return file_proto_project_proto_rawDescGZIP(), []int{6}
}

func (x *GetAllDepositsResponse) GetDeposits() []*Deposit {
	if x != nil {
		return x.Deposits
	}
	return nil
}

type GetDepositByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDepositByIDRequest) Reset() {
	*x = GetDepositByIDRequest{}
	mi := &file_proto_project_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDepositByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDepositByIDRequest) ProtoMessage() {}

func (x *GetDepositByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDepositByIDRequest.ProtoReflect.Descriptor instead.
func (*GetDepositByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_project_proto_rawDescGZIP(), []int{7}
}

func (x *GetDepositByIDRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetDepositByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deposit       *Deposit               `protobuf:"bytes,1,opt,name=deposit,proto3" json:"deposit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDepositByIDResponse) Reset() {
	*x = GetDepositByIDResponse{}
	mi := &file_proto_project_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDepositByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDepositByIDResponse) ProtoMessage() {}

func (x *GetDepositByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDepositByIDResponse.ProtoReflect.Descriptor instead.
func (*GetDepositByIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_project_proto_rawDescGZIP(), []int{8}
}

func (x *GetDepositByIDResponse) GetDeposit() *Deposit {
	if x != nil {
		return x.Deposit
	}
	return nil
}

type GetBondsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Board         string                 `protobuf:"bytes,1,opt,name=board,proto3" json:"board,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBondsRequest) Reset() {
	*x = GetBondsRequest{}
	mi := &file_proto_project_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBondsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBondsRequest) ProtoMessage() {}

func (x *GetBondsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBondsRequest.ProtoReflect.Descriptor instead.
func (*GetBondsRequest) Descriptor() ([]byte, []int) {
	return file_proto_project_proto_rawDescGZIP(), []int{9}
}

func (x *GetBondsRequest) GetBoard() string {
	if x != nil {
		return x.Board
	}
	return ""
}

type GetBondsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bonds         []*Bond                `protobuf:"bytes,1,rep,name=bonds,proto3" json:"bonds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBondsResponse) Reset() {
	*x = GetBondsResponse{}
	mi := &file_proto_project_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBondsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBondsResponse) ProtoMessage() {}

func (x *GetBondsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBondsResponse.ProtoReflect.Descriptor instead.
func (*GetBondsResponse) Descriptor() ([]byte, []int) {
	return file_proto_project_proto_rawDescGZIP(), []int{10}
}

func (x *GetBondsResponse) GetBonds() []*Bond {
	if x != nil {
		return x.Bonds
	}
	return nil
}

type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sum           int32                  `protobuf:"varint,1,opt,name=sum,proto3" json:"sum,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_proto_project_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_proto_project_proto_rawDescGZIP(), []int{11}
}

func (x *QueryRequest) GetSum() int32 {
	if x != nil {
		return x.Sum
	}
	return 0
}

func (x *QueryRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type QueryResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Results       map[string]*ProductList `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_proto_project_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_proto_project_proto_rawDescGZIP(), []int{12}
}

func (x *QueryResponse) GetResults() map[string]*ProductList {
	if x != nil {
		return x.Results
	}
	return nil
}

type ProductList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*ProductResult       `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductList) Reset() {
	*x = ProductList{}
	mi := &file_proto_project_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductList) ProtoMessage() {}

func (x *ProductList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductList.ProtoReflect.Descriptor instead.
func (*ProductList) Descriptor() ([]byte, []int) {
	return file_proto_project_proto_rawDescGZIP(), []int{13}
}

func (x *ProductList) GetProducts() []*ProductResult {
	if x != nil {
		return x.Products
	}
	return nil
}

type ProductResult struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Type            string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Secid           string                 `protobuf:"bytes,2,opt,name=secid,proto3" json:"secid,omitempty"`
	ShortName       string                 `protobuf:"bytes,3,opt,name=short_name,json=shortName,proto3" json:"short_name,omitempty"`
	YieldToMaturity float32                `protobuf:"fixed32,4,opt,name=yield_to_maturity,json=yieldToMaturity,proto3" json:"yield_to_maturity,omitempty"`
	CouponPercent   float32                `protobuf:"fixed32,5,opt,name=coupon_percent,json=couponPercent,proto3" json:"coupon_percent,omitempty"`
	CouponValue     float32                `protobuf:"fixed32,6,opt,name=coupon_value,json=couponValue,proto3" json:"coupon_value,omitempty"`
	FaceValue       float32                `protobuf:"fixed32,7,opt,name=face_value,json=faceValue,proto3" json:"face_value,omitempty"`
	Last            float32                `protobuf:"fixed32,8,opt,name=last,proto3" json:"last,omitempty"`
	MatDate         string                 `protobuf:"bytes,9,opt,name=mat_date,json=matDate,proto3" json:"mat_date,omitempty"`
	Earnings        float32                `protobuf:"fixed32,10,opt,name=earnings,proto3" json:"earnings,omitempty"`
	Link            string                 `protobuf:"bytes,11,opt,name=link,proto3" json:"link,omitempty"`
	Apr             float32                `protobuf:"fixed32,12,opt,name=apr,proto3" json:"apr,omitempty"`
	AmountFrom      int32                  `protobuf:"varint,13,opt,name=amount_from,json=amountFrom,proto3" json:"amount_from,omitempty"`
	AmountTo        int32                  `protobuf:"varint,14,opt,name=amount_to,json=amountTo,proto3" json:"amount_to,omitempty"`
	HasAmountTo     bool                   `protobuf:"varint,15,opt,name=has_amount_to,json=hasAmountTo,proto3" json:"has_amount_to,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProductResult) Reset() {
	*x = ProductResult{}
	mi := &file_proto_project_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductResult) ProtoMessage() {}

func (x *ProductResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductResult.ProtoReflect.Descriptor instead.
func (*ProductResult) Descriptor() ([]byte, []int) {
	return file_proto_project_proto_rawDescGZIP(), []int{14}
}

func (x *ProductResult) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ProductResult) GetSecid() string {
	if x != nil {
		return x.Secid
	}
	return ""
}

func (x *ProductResult) GetShortName() string {
	if x != nil {
		return x.ShortName
	}
	return ""
}

func (x *ProductResult) GetYieldToMaturity() float32 {
	if x != nil {
		return x.YieldToMaturity
	}
	return 0
}

func (x *ProductResult) GetCouponPercent() float32 {
	if x != nil {
		return x.CouponPercent
	}
	return 0
}

func (x *ProductResult) GetCouponValue() float32 {
	if x != nil {
		return x.CouponValue
	}
	return 0
}

func (x *ProductResult) GetFaceValue() float32 {
	if x != nil {
		return x.FaceValue
	}
	return 0
}

func (x *ProductResult) GetLast() float32 {
	if x != nil {
		return x.Last
	}
	return 0
}

func (x *ProductResult) GetMatDate() string {
	if x != nil {
		return x.MatDate
	}
	return ""
}

func (x *ProductResult) GetEarnings() float32 {
	if x != nil {
		return x.Earnings
	}
	return 0
}

func (x *ProductResult) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *ProductResult) GetApr() float32 {
	if x != nil {
		return x.Apr
	}
	return 0
}

func (x *ProductResult) GetAmountFrom() int32 {
	if x != nil {
		return x.AmountFrom
	}
	return 0
}

func (x *ProductResult) GetAmountTo() int32 {
	if x != nil {
		return x.AmountTo
	}
	return 0
}

func (x *ProductResult) GetHasAmountTo() bool {
	if x != nil {
		return x.HasAmountTo
	}
	return false
}

type Deposit struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	Id                          int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductUrl                  string                 `protobuf:"bytes,2,opt,name=product_url,json=productUrl,proto3" json:"product_url,omitempty"`
	RateMin                     float32                `protobuf:"fixed32,3,opt,name=rate_min,json=rateMin,proto3" json:"rate_min,omitempty"`
	RateMax                     float32                `protobuf:"fixed32,4,opt,name=rate_max,json=rateMax,proto3" json:"rate_max,omitempty"`
	AmountFrom                  int32                  `protobuf:"varint,5,opt,name=amount_from,json=amountFrom,proto3" json:"amount_from,omitempty"`
	AmountTo                    int32                  `protobuf:"varint,6,opt,name=amount_to,json=amountTo,proto3" json:"amount_to,omitempty"`
	HasAmountTo                 bool                   `protobuf:"varint,7,opt,name=has_amount_to,json=hasAmountTo,proto3" json:"has_amount_to,omitempty"`
	PeriodFrom                  int32                  `protobuf:"varint,8,opt,name=period_from,json=periodFrom,proto3" json:"period_from,omitempty"`
	PeriodTo                    int32                  `protobuf:"varint,9,opt,name=period_to,json=periodTo,proto3" json:"period_to,omitempty"`
	HasPeriodTo                 bool                   `protobuf:"varint,10,opt,name=has_period_to,json=hasPeriodTo,proto3" json:"has_period_to,omitempty"`
	ProductName                 string                 `protobuf:"bytes,11,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	BankName                    string                 `protobuf:"bytes,12,opt,name=bank_name,json=bankName,proto3" json:"bank_name,omitempty"`
	DepositName                 string                 `protobuf:"bytes,13,opt,name=deposit_name,json=depositName,proto3" json:"deposit_name,omitempty"`
	IsSavingAccount             bool                   `protobuf:"varint,14,opt,name=is_saving_account,json=isSavingAccount,proto3" json:"is_saving_account,omitempty"`
	IsChildrenDeposit           bool                   `protobuf:"varint,15,opt,name=is_children_deposit,json=isChildrenDeposit,proto3" json:"is_children_deposit,omitempty"`
	IsPensionDeposit            bool                   `protobuf:"varint,16,opt,name=is_pension_deposit,json=isPensionDeposit,proto3" json:"is_pension_deposit,omitempty"`
	FeatureList                 map[string]bool        `protobuf:"bytes,17,rep,name=feature_list,json=featureList,proto3" json:"feature_list,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	SpecialRestrictions         string                 `protobuf:"bytes,18,opt,name=special_restrictions,json=specialRestrictions,proto3" json:"special_restrictions,omitempty"`
	HasSpecialRestrictions      bool                   `protobuf:"varint,19,opt,name=has_special_restrictions,json=hasSpecialRestrictions,proto3" json:"has_special_restrictions,omitempty"`
	SpecialTypeListNames        []string               `protobuf:"bytes,20,rep,name=special_type_list_names,json=specialTypeListNames,proto3" json:"special_type_list_names,omitempty"`
	EfficientRate               float32                `protobuf:"fixed32,21,opt,name=efficient_rate,json=efficientRate,proto3" json:"efficient_rate,omitempty"`
	CapitalizationPeriods       map[string]string      `protobuf:"bytes,22,rep,name=capitalization_periods,json=capitalizationPeriods,proto3" json:"capitalization_periods,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	IsPartialWithdrawalPossible bool                   `protobuf:"varint,23,opt,name=is_partial_withdrawal_possible,json=isPartialWithdrawalPossible,proto3" json:"is_partial_withdrawal_possible,omitempty"`
	IsReplenishmentPossible     bool                   `protobuf:"varint,24,opt,name=is_replenishment_possible,json=isReplenishmentPossible,proto3" json:"is_replenishment_possible,omitempty"`
	IsProlongationPossible      bool                   `protobuf:"varint,25,opt,name=is_prolongation_possible,json=isProlongationPossible,proto3" json:"is_prolongation_possible,omitempty"`
	HasIsProlongationPossible   bool                   `protobuf:"varint,26,opt,name=has_is_prolongation_possible,json=hasIsProlongationPossible,proto3" json:"has_is_prolongation_possible,omitempty"`
	ProlongationMax             int32                  `protobuf:"varint,27,opt,name=prolongation_max,json=prolongationMax,proto3" json:"prolongation_max,omitempty"`
	HasProlongationMax          bool                   `protobuf:"varint,28,opt,name=has_prolongation_max,json=hasProlongationMax,proto3" json:"has_prolongation_max,omitempty"`
	ProlongationComment         string                 `protobuf:"bytes,29,opt,name=prolongation_comment,json=prolongationComment,proto3" json:"prolongation_comment,omitempty"`
	HasProlongationComment      bool                   `protobuf:"varint,30,opt,name=has_prolongation_comment,json=hasProlongationComment,proto3" json:"has_prolongation_comment,omitempty"`
	ProlongationCommentHtml     string                 `protobuf:"bytes,31,opt,name=prolongation_comment_html,json=prolongationCommentHtml,proto3" json:"prolongation_comment_html,omitempty"`
	HasProlongationCommentHtml  bool                   `protobuf:"varint,32,opt,name=has_prolongation_comment_html,json=hasProlongationCommentHtml,proto3" json:"has_prolongation_comment_html,omitempty"`
	IsInOfficeOpeningPossible   bool                   `protobuf:"varint,33,opt,name=is_in_office_opening_possible,json=isInOfficeOpeningPossible,proto3" json:"is_in_office_opening_possible,omitempty"`
	DetailedConditions          string                 `protobuf:"bytes,34,opt,name=detailed_conditions,json=detailedConditions,proto3" json:"detailed_conditions,omitempty"`
	HasDetailedConditions       bool                   `protobuf:"varint,35,opt,name=has_detailed_conditions,json=hasDetailedConditions,proto3" json:"has_detailed_conditions,omitempty"`
	IsRateIncreasePossible      bool                   `protobuf:"varint,36,opt,name=is_rate_increase_possible,json=isRateIncreasePossible,proto3" json:"is_rate_increase_possible,omitempty"`
	PercentCalculation          string                 `protobuf:"bytes,37,opt,name=percent_calculation,json=percentCalculation,proto3" json:"percent_calculation,omitempty"`
	HasPercentCalculation       bool                   `protobuf:"varint,38,opt,name=has_percent_calculation,json=hasPercentCalculation,proto3" json:"has_percent_calculation,omitempty"`
	IsNewClient                 bool                   `protobuf:"varint,39,opt,name=is_new_client,json=isNewClient,proto3" json:"is_new_client,omitempty"`
	NewClientComment            string                 `protobuf:"bytes,40,opt,name=new_client_comment,json=newClientComment,proto3" json:"new_client_comment,omitempty"`
	HasNewClientComment         bool                   `protobuf:"varint,41,opt,name=has_new_client_comment,json=hasNewClientComment,proto3" json:"has_new_client_comment,omitempty"`
	IsNewMoney                  bool                   `protobuf:"varint,42,opt,name=is_new_money,json=isNewMoney,proto3" json:"is_new_money,omitempty"`
	NewMoneyComment             string                 `protobuf:"bytes,43,opt,name=new_money_comment,json=newMoneyComment,proto3" json:"new_money_comment,omitempty"`
	HasNewMoneyComment          bool                   `protobuf:"varint,44,opt,name=has_new_money_comment,json=hasNewMoneyComment,proto3" json:"has_new_money_comment,omitempty"`
	IsKeyRateLinked             bool                   `protobuf:"varint,45,opt,name=is_key_rate_linked,json=isKeyRateLinked,proto3" json:"is_key_rate_linked,omitempty"`
	KeyRateLinkedComment        string                 `protobuf:"bytes,46,opt,name=key_rate_linked_comment,json=keyRateLinkedComment,proto3" json:"key_rate_linked_comment,omitempty"`
	HasKeyRateLinkedComment     bool                   `protobuf:"varint,47,opt,name=has_key_rate_linked_comment,json=hasKeyRateLinkedComment,proto3" json:"has_key_rate_linked_comment,omitempty"`
	RatesExtremum               *RatesExtremum         `protobuf:"bytes,48,opt,name=rates_extremum,json=ratesExtremum,proto3" json:"rates_extremum,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *Deposit) Reset() {
	*x = Deposit{}
	mi := &file_proto_project_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Deposit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deposit) ProtoMessage() {}

func (x *Deposit) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deposit.ProtoReflect.Descriptor instead.
func (*Deposit) Descriptor() ([]byte, []int) {
	return file_proto_project_proto_rawDescGZIP(), []int{15}
}

func (x *Deposit) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Deposit) GetProductUrl() string {
	if x != nil {
		return x.ProductUrl
	}
	return ""
}

func (x *Deposit) GetRateMin() float32 {
	if x != nil {
		return x.RateMin
	}
	return 0
}

func (x *Deposit) GetRateMax() float32 {
	if x != nil {
		return x.RateMax
	}
	return 0
}

func (x *Deposit) GetAmountFrom() int32 {
	if x != nil {
		return x.AmountFrom
	}
	return 0
}

func (x *Deposit) GetAmountTo() int32 {
	if x != nil {
		return x.AmountTo
	}
	return 0
}

func (x *Deposit) GetHasAmountTo() bool {
	if x != nil {
		return x.HasAmountTo
	}
	return false
}

func (x *Deposit) GetPeriodFrom() int32 {
	if x != nil {
		return x.PeriodFrom
	}
	return 0
}

func (x *Deposit) GetPeriodTo() int32 {
	if x != nil {
		return x.PeriodTo
	}
	return 0
}

func (x *Deposit) GetHasPeriodTo() bool {
	if x != nil {
		return x.HasPeriodTo
	}
	return false
}

func (x *Deposit) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *Deposit) GetBankName() string {
	if x != nil {
		return x.BankName
	}
	return ""
}

func (x *Deposit) GetDepositName() string {
	if x != nil {
		return x.DepositName
	}
	return ""
}

func (x *Deposit) GetIsSavingAccount() bool {
	if x != nil {
		return x.IsSavingAccount
	}
	return false
}

func (x *Deposit) GetIsChildrenDeposit() bool {
	if x != nil {
		return x.IsChildrenDeposit
	}
	return false
}

func (x *Deposit) GetIsPensionDeposit() bool {
	if x != nil {
		return x.IsPensionDeposit
	}
	return false
}

func (x *Deposit) GetFeatureList() map[string]bool {
	if x != nil {
		return x.FeatureList
	}
	return nil
}

func (x *Deposit) GetSpecialRestrictions() string {
	if x != nil {
		return x.SpecialRestrictions
	}
	return ""
}

func (x *Deposit) GetHasSpecialRestrictions() bool {
	if x != nil {
		return x.HasSpecialRestrictions
	}
	return false
}

func (x *Deposit) GetSpecialTypeListNames() []string {
	if x != nil {
		return x.SpecialTypeListNames
	}
	return nil
}

func (x *Deposit) GetEfficientRate() float32 {
	if x != nil {
		return x.EfficientRate
	}
	return 0
}

func (x *Deposit) GetCapitalizationPeriods() map[string]string {
	if x != nil {
		return x.CapitalizationPeriods
	}
	return nil
}

func (x *Deposit) GetIsPartialWithdrawalPossible() bool {
	if x != nil {
		return x.IsPartialWithdrawalPossible
	}
	return false
}

func (x *Deposit) GetIsReplenishmentPossible() bool {
	if x != nil {
		return x.IsReplenishmentPossible
	}
	return false
}

func (x *Deposit) GetIsProlongationPossible() bool {
	if x != nil {
		return x.IsProlongationPossible
	}
	return false
}

func (x *Deposit) GetHasIsProlongationPossible() bool {
	if x != nil {
		return x.HasIsProlongationPossible
	}
	return false
}

func (x *Deposit) GetProlongationMax() int32 {
	if x != nil {
		return x.ProlongationMax
	}
	return 0
}

func (x *Deposit) GetHasProlongationMax() bool {
	if x != nil {
		return x.HasProlongationMax
	}
	return false
}

func (x *Deposit) GetProlongationComment() string {
	if x != nil {
		return x.ProlongationComment
	}
	return ""
}

func (x *Deposit) GetHasProlongationComment() bool {
	if x != nil {
		return x.HasProlongationComment
	}
	return false
}

func (x *Deposit) GetProlongationCommentHtml() string {
	if x != nil {
		return x.ProlongationCommentHtml
	}
	return ""
}

func (x *Deposit) GetHasProlongationCommentHtml() bool {
	if x != nil {
		return x.HasProlongationCommentHtml
	}
	return false
}

func (x *Deposit) GetIsInOfficeOpeningPossible() bool {
	if x != nil {
		return x.IsInOfficeOpeningPossible
	}
	return false
}

func (x *Deposit) GetDetailedConditions() string {
	if x != nil {
		return x.DetailedConditions
	}
	return ""
}

func (x *Deposit) GetHasDetailedConditions() bool {
	if x != nil {
		return x.HasDetailedConditions
	}
	return false
}

func (x *Deposit) GetIsRateIncreasePossible() bool {
	if x != nil {
		return x.IsRateIncreasePossible
	}
	return false
}

func (x *Deposit) GetPercentCalculation() string {
	if x != nil {
		return x.PercentCalculation
	}
	return ""
}

func (x *Deposit) GetHasPercentCalculation() bool {
	if x != nil {
		return x.HasPercentCalculation
	}
	return false
}

func (x *Deposit) GetIsNewClient() bool {
	if x != nil {
		return x.IsNewClient
	}
	return false
}

func (x *Deposit) GetNewClientComment() string {
	if x != nil {
		return x.NewClientComment
	}
	return ""
}

func (x *Deposit) GetHasNewClientComment() bool {
	if x != nil {
		return x.HasNewClientComment
	}
	return false
}

func (x *Deposit) GetIsNewMoney() bool {
	if x != nil {
		return x.IsNewMoney
	}
	return false
}

func (x *Deposit) GetNewMoneyComment() string {
	if x != nil {
		return x.NewMoneyComment
	}
	return ""
}

func (x *Deposit) GetHasNewMoneyComment() bool {
	if x != nil {
		return x.HasNewMoneyComment
	}
	return false
}

func (x *Deposit) GetIsKeyRateLinked() bool {
	if x != nil {
		return x.IsKeyRateLinked
	}
	return false
}

func (x *Deposit) GetKeyRateLinkedComment() string {
	if x != nil {
		return x.KeyRateLinkedComment
	}
	return ""
}

func (x *Deposit) GetHasKeyRateLinkedComment() bool {
	if x != nil {
		return x.HasKeyRateLinkedComment
	}
	return false
}

func (x *Deposit) GetRatesExtremum() *RatesExtremum {
	if x != nil {
		return x.RatesExtremum
	}
	return nil
}

type RatesExtremum struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MinRate       float32                `protobuf:"fixed32,1,opt,name=min_rate,json=minRate,proto3" json:"min_rate,omitempty"`
	MaxRate       float32                `protobuf:"fixed32,2,opt,name=max_rate,json=maxRate,proto3" json:"max_rate,omitempty"`
	MinAmount     int32                  `protobuf:"varint,3,opt,name=min_amount,json=minAmount,proto3" json:"min_amount,omitempty"`
	MaxAmount     int32                  `protobuf:"varint,4,opt,name=max_amount,json=maxAmount,proto3" json:"max_amount,omitempty"`
	HasMaxAmount  bool                   `protobuf:"varint,5,opt,name=has_max_amount,json=hasMaxAmount,proto3" json:"has_max_amount,omitempty"`
	MinPeriod     int32                  `protobuf:"varint,6,opt,name=min_period,json=minPeriod,proto3" json:"min_period,omitempty"`
	MaxPeriod     int32                  `protobuf:"varint,7,opt,name=max_period,json=maxPeriod,proto3" json:"max_period,omitempty"`
	HasMaxPeriod  bool                   `protobuf:"varint,8,opt,name=has_max_period,json=hasMaxPeriod,proto3" json:"has_max_period,omitempty"`
	RatesTable    []*RatesTable          `protobuf:"bytes,9,rep,name=rates_table,json=ratesTable,proto3" json:"rates_table,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RatesExtremum) Reset() {
	*x = RatesExtremum{}
	mi := &file_proto_project_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RatesExtremum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RatesExtremum) ProtoMessage() {}

func (x *RatesExtremum) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RatesExtremum.ProtoReflect.Descriptor instead.
func (*RatesExtremum) Descriptor() ([]byte, []int) {
	return file_proto_project_proto_rawDescGZIP(), []int{16}
}

func (x *RatesExtremum) GetMinRate() float32 {
	if x != nil {
		return x.MinRate
	}
	return 0
}

func (x *RatesExtremum) GetMaxRate() float32 {
	if x != nil {
		return x.MaxRate
	}
	return 0
}

func (x *RatesExtremum) GetMinAmount() int32 {
	if x != nil {
		return x.MinAmount
	}
	return 0
}

func (x *RatesExtremum) GetMaxAmount() int32 {
	if x != nil {
		return x.MaxAmount
	}
	return 0
}

func (x *RatesExtremum) GetHasMaxAmount() bool {
	if x != nil {
		return x.HasMaxAmount
	}
	return false
}

func (x *RatesExtremum) GetMinPeriod() int32 {
	if x != nil {
		return x.MinPeriod
	}
	return 0
}

func (x *RatesExtremum) GetMaxPeriod() int32 {
	if x != nil {
		return x.MaxPeriod
	}
	return 0
}

func (x *RatesExtremum) GetHasMaxPeriod() bool {
	if x != nil {
		return x.HasMaxPeriod
	}
	return false
}

func (x *RatesExtremum) GetRatesTable() []*RatesTable {
	if x != nil {
		return x.RatesTable
	}
	return nil
}

type RatesTable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rate          float32                `protobuf:"fixed32,1,opt,name=rate,proto3" json:"rate,omitempty"`
	FromNotation  string                 `protobuf:"bytes,2,opt,name=from_notation,json=fromNotation,proto3" json:"from_notation,omitempty"`
	ToNotation    string                 `protobuf:"bytes,3,opt,name=to_notation,json=toNotation,proto3" json:"to_notation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RatesTable) Reset() {
	*x = RatesTable{}
	mi := &file_proto_project_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RatesTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RatesTable) ProtoMessage() {}

func (x *RatesTable) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RatesTable.ProtoReflect.Descriptor instead.
func (*RatesTable) Descriptor() ([]byte, []int) {
	return file_proto_project_proto_rawDescGZIP(), []int{17}
}

func (x *RatesTable) GetRate() float32 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *RatesTable) GetFromNotation() string {
	if x != nil {
		return x.FromNotation
	}
	return ""
}

func (x *RatesTable) GetToNotation() string {
	if x != nil {
		return x.ToNotation
	}
	return ""
}

type Bond struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Isin               string                 `protobuf:"bytes,1,opt,name=isin,proto3" json:"isin,omitempty"`
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	NameShort          string                 `protobuf:"bytes,3,opt,name=name_short,json=nameShort,proto3" json:"name_short,omitempty"`
	Type               string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	ListLevel          string                 `protobuf:"bytes,5,opt,name=list_level,json=listLevel,proto3" json:"list_level,omitempty"`
	Status             string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	RegNumber          string                 `protobuf:"bytes,7,opt,name=reg_number,json=regNumber,proto3" json:"reg_number,omitempty"`
	IssueSize          int32                  `protobuf:"varint,8,opt,name=issue_size,json=issueSize,proto3" json:"issue_size,omitempty"`
	ListVolume         int32                  `protobuf:"varint,9,opt,name=list_volume,json=listVolume,proto3" json:"list_volume,omitempty"`
	MinStep            float32                `protobuf:"fixed32,10,opt,name=min_step,json=minStep,proto3" json:"min_step,omitempty"`
	Decimals           string                 `protobuf:"bytes,11,opt,name=decimals,proto3" json:"decimals,omitempty"`
	Emitent            string                 `protobuf:"bytes,12,opt,name=emitent,proto3" json:"emitent,omitempty"`
	MatDate            string                 `protobuf:"bytes,13,opt,name=mat_date,json=matDate,proto3" json:"mat_date,omitempty"`
	InitialFaceValue   float32                `protobuf:"fixed32,14,opt,name=initial_face_value,json=initialFaceValue,proto3" json:"initial_face_value,omitempty"`
	FaceValue          float32                `protobuf:"fixed32,15,opt,name=face_value,json=faceValue,proto3" json:"face_value,omitempty"`
	YieldToMaturity    float32                `protobuf:"fixed32,16,opt,name=yield_to_maturity,json=yieldToMaturity,proto3" json:"yield_to_maturity,omitempty"`
	HasYieldToMaturity bool                   `protobuf:"varint,17,opt,name=has_yield_to_maturity,json=hasYieldToMaturity,proto3" json:"has_yield_to_maturity,omitempty"`
	CouponPeriod       int32                  `protobuf:"varint,18,opt,name=coupon_period,json=couponPeriod,proto3" json:"coupon_period,omitempty"`
	CouponPercent      float32                `protobuf:"fixed32,19,opt,name=coupon_percent,json=couponPercent,proto3" json:"coupon_percent,omitempty"`
	CouponValue        float32                `protobuf:"fixed32,20,opt,name=coupon_value,json=couponValue,proto3" json:"coupon_value,omitempty"`
	AccruedInt         float32                `protobuf:"fixed32,21,opt,name=accrued_int,json=accruedInt,proto3" json:"accrued_int,omitempty"`
	Currency           string                 `protobuf:"bytes,22,opt,name=currency,proto3" json:"currency,omitempty"`
	EmitentTitle       string                 `protobuf:"bytes,23,opt,name=emitent_title,json=emitentTitle,proto3" json:"emitent_title,omitempty"`
	EmitentInn         string                 `protobuf:"bytes,24,opt,name=emitent_inn,json=emitentInn,proto3" json:"emitent_inn,omitempty"`
	BoardId            string                 `protobuf:"bytes,25,opt,name=board_id,json=boardId,proto3" json:"board_id,omitempty"`
	Secid              string                 `protobuf:"bytes,26,opt,name=secid,proto3" json:"secid,omitempty"`
	ShortName          string                 `protobuf:"bytes,27,opt,name=short_name,json=shortName,proto3" json:"short_name,omitempty"`
	Last               float32                `protobuf:"fixed32,28,opt,name=last,proto3" json:"last,omitempty"`
	HasLast            bool                   `protobuf:"varint,29,opt,name=has_last,json=hasLast,proto3" json:"has_last,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Bond) Reset() {
	*x = Bond{}
	mi := &file_proto_project_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bond) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bond) ProtoMessage() {}

func (x *Bond) ProtoReflect() protoreflect.Message {
	mi := &file_proto_project_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bond.ProtoReflect.Descriptor instead.
func (*Bond) Descriptor() ([]byte, []int) {
	return file_proto_project_proto_rawDescGZIP(), []int{18}
}

func (x *Bond) GetIsin() string {
	if x != nil {
		return x.Isin
	}
	return ""
}

func (x *Bond) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Bond) GetNameShort() string {
	if x != nil {
		return x.NameShort
	}
	return ""
}

func (x *Bond) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Bond) GetListLevel() string {
	if x != nil {
		return x.ListLevel
	}
	return ""
}

func (x *Bond) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Bond) GetRegNumber() string {
	if x != nil {
		return x.RegNumber
	}
	return ""
}

func (x *Bond) GetIssueSize() int32 {
	if x != nil {
		return x.IssueSize
	}
	return 0
}

func (x *Bond) GetListVolume() int32 {
	if x != nil {
		return x.ListVolume
	}
	return 0
}

func (x *Bond) GetMinStep() float32 {
	if x != nil {
		return x.MinStep
	}
	return 0
}

func (x *Bond) GetDecimals() string {
	if x != nil {
		return x.Decimals
	}
	return ""
}

func (x *Bond) GetEmitent() string {
	if x != nil {
		return x.Emitent
	}
	return ""
}

func (x *Bond) GetMatDate() string {
	if x != nil {
		return x.MatDate
	}
	return ""
}

func (x *Bond) GetInitialFaceValue() float32 {
	if x != nil {
		return x.InitialFaceValue
	}
	return 0
}

func (x *Bond) GetFaceValue() float32 {
	if x != nil {
		return x.FaceValue
	}
	return 0
}

func (x *Bond) GetYieldToMaturity() float32 {
	if x != nil {
		return x.YieldToMaturity
	}
	return 0
}

func (x *Bond) GetHasYieldToMaturity() bool {
	if x != nil {
		return x.HasYieldToMaturity
	}
	return false
}

func (x *Bond) GetCouponPeriod() int32 {
	if x != nil {
		return x.CouponPeriod
	}
	return 0
}

func (x *Bond) GetCouponPercent() float32 {
	if x != nil {
		return x.CouponPercent
	}
	return 0
}

func (x *Bond) GetCouponValue() float32 {
	if x != nil {
		return x.CouponValue
	}
	return 0
}

func (x *Bond) GetAccruedInt() float32 {
	if x != nil {
		return x.AccruedInt
	}
	return 0
}

func (x *Bond) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Bond) GetEmitentTitle() string {
	if x != nil {
		return x.EmitentTitle
	}
	return ""
}

func (x *Bond) GetEmitentInn() string {
	if x != nil {
		return x.EmitentInn
	}
	return ""
}

func (x *Bond) GetBoardId() string {
	if x != nil {
		return x.BoardId
	}
	return ""
}

func (x *Bond) GetSecid() string {
	if x != nil {
		return x.Secid
	}
	return ""
}

func (x *Bond) GetShortName() string {
	if x != nil {
		return x.ShortName
	}
	return ""
}

func (x *Bond) GetLast() float32 {
	if x != nil {
		return x.Last
	}
	return 0
}

func (x *Bond) GetHasLast() bool {
	if x != nil {
		return x.HasLast
	}
	return false
}

var File_proto_project_proto protoreflect.FileDescriptor

const file_proto_project_proto_rawDesc = "" +
	"\n" +
	"\x13proto/project.proto\x12\aproject\"\x11\n" +
	"\x0fGetStatsRequest\"?\n" +
	"\x10GetStatsResponse\x12+\n" +
	"\x05stats\x18\x01 \x03(\v2\x15.project.CategoryStatR\x05stats\"\x86\x01\n" +
	"\fCategoryStat\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12\x1f\n" +
	"\vaverage_apr\x18\x03 \x01(\x02R\n" +
	"averageApr\x12%\n" +
	"\x0eaverage_income\x18\x04 \x01(\x02R\raverageIncome\"\x0e\n" +
	"\fFetchRequest\")\n" +
	"\rFetchResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x17\n" +
	"\x15GetAllDepositsRequest\"F\n" +
	"\x16GetAllDepositsResponse\x12,\n" +
	"\bdeposits\x18\x01 \x03(\v2\x10.project.DepositR\bdeposits\"'\n" +
	"\x15GetDepositByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"D\n" +
	"\x16GetDepositByIDResponse\x12*\n" +
	"\adeposit\x18\x01 \x01(\v2\x10.project.DepositR\adeposit\"'\n" +
	"\x0fGetBondsRequest\x12\x14\n" +
	"\x05board\x18\x01 \x01(\tR\x05board\"7\n" +
	"\x10GetBondsResponse\x12#\n" +
	"\x05bonds\x18\x01 \x03(\v2\r.project.BondR\x05bonds\"6\n" +
	"\fQueryRequest\x12\x10\n" +
	"\x03sum\x18\x01 \x01(\x05R\x03sum\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"\xa0\x01\n" +
	"\rQueryResponse\x12=\n" +
	"\aresults\x18\x01 \x03(\v2#.project.QueryResponse.ResultsEntryR\aresults\x1aP\n" +
	"\fResultsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.project.ProductListR\x05value:\x028\x01\"A\n" +
	"\vProductList\x122\n" +
	"\bproducts\x18\x01 \x03(\v2\x16.project.ProductResultR\bproducts\"\xc0\x03\n" +
	"\rProductResult\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05secid\x18\x02 \x01(\tR\x05secid\x12\x1d\n" +
	"\n" +
	"short_name\x18\x03 \x01(\tR\tshortName\x12*\n" +
	"\x11yield_to_maturity\x18\x04 \x01(\x02R\x0fyieldToMaturity\x12%\n" +
	"\x0ecoupon_percent\x18\x05 \x01(\x02R\rcouponPercent\x12!\n" +
	"\fcoupon_value\x18\x06 \x01(\x02R\vcouponValue\x12\x1d\n" +
	"\n" +
	"face_value\x18\a \x01(\x02R\tfaceValue\x12\x12\n" +
	"\x04last\x18\b \x01(\x02R\x04last\x12\x19\n" +
	"\bmat_date\x18\t \x01(\tR\amatDate\x12\x1a\n" +
	"\bearnings\x18\n" +
	" \x01(\x02R\bearnings\x12\x12\n" +
	"\x04link\x18\v \x01(\tR\x04link\x12\x10\n" +
	"\x03apr\x18\f \x01(\x02R\x03apr\x12\x1f\n" +
	"\vamount_from\x18\r \x01(\x05R\n" +
	"amountFrom\x12\x1b\n" +
	"\tamount_to\x18\x0e \x01(\x05R\bamountTo\x12\"\n" +
	"\rhas_amount_to\x18\x0f \x01(\bR\vhasAmountTo\"\x9d\x13\n" +
	"\aDeposit\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1f\n" +
	"\vproduct_url\x18\x02 \x01(\tR\n" +
	"productUrl\x12\x19\n" +
	"\brate_min\x18\x03 \x01(\x02R\arateMin\x12\x19\n" +
	"\brate_max\x18\x04 \x01(\x02R\arateMax\x12\x1f\n" +
	"\vamount_from\x18\x05 \x01(\x05R\n" +
	"amountFrom\x12\x1b\n" +
	"\tamount_to\x18\x06 \x01(\x05R\bamountTo\x12\"\n" +
	"\rhas_amount_to\x18\a \x01(\bR\vhasAmountTo\x12\x1f\n" +
	"\vperiod_from\x18\b \x01(\x05R\n" +
	"periodFrom\x12\x1b\n" +
	"\tperiod_to\x18\t \x01(\x05R\bperiodTo\x12\"\n" +
	"\rhas_period_to\x18\n" +
	" \x01(\bR\vhasPeriodTo\x12!\n" +
	"\fproduct_name\x18\v \x01(\tR\vproductName\x12\x1b\n" +
	"\tbank_name\x18\f \x01(\tR\bbankName\x12!\n" +
	"\fdeposit_name\x18\r \x01(\tR\vdepositName\x12*\n" +
	"\x11is_saving_account\x18\x0e \x01(\bR\x0fisSavingAccount\x12.\n" +
	"\x13is_children_deposit\x18\x0f \x01(\bR\x11isChildrenDeposit\x12,\n" +
	"\x12is_pension_deposit\x18\x10 \x01(\bR\x10isPensionDeposit\x12D\n" +
	"\ffeature_list\x18\x11 \x03(\v2!.project.Deposit.FeatureListEntryR\vfeatureList\x121\n" +
	"\x14special_restrictions\x18\x12 \x01(\tR\x13specialRestrictions\x128\n" +
	"\x18has_special_restrictions\x18\x13 \x01(\bR\x16hasSpecialRestrictions\x125\n" +
	"\x17special_type_list_names\x18\x14 \x03(\tR\x14specialTypeListNames\x12%\n" +
	"\x0eefficient_rate\x18\x15 \x01(\x02R\refficientRate\x12b\n" +
	"\x16capitalization_periods\x18\x16 \x03(\v2+.project.Deposit.CapitalizationPeriodsEntryR\x15capitalizationPeriods\x12C\n" +
	"\x1eis_partial_withdrawal_possible\x18\x17 \x01(\bR\x1bisPartialWithdrawalPossible\x12:\n" +
	"\x19is_replenishment_possible\x18\x18 \x01(\bR\x17isReplenishmentPossible\x128\n" +
	"\x18is_prolongation_possible\x18\x19 \x01(\bR\x16isProlongationPossible\x12?\n" +
	"\x1chas_is_prolongation_possible\x18\x1a \x01(\bR\x19hasIsProlongationPossible\x12)\n" +
	"\x10prolongation_max\x18\x1b \x01(\x05R\x0fprolongationMax\x120\n" +
	"\x14has_prolongation_max\x18\x1c \x01(\bR\x12hasProlongationMax\x121\n" +
	"\x14prolongation_comment\x18\x1d \x01(\tR\x13prolongationComment\x128\n" +
	"\x18has_prolongation_comment\x18\x1e \x01(\bR\x16hasProlongationComment\x12:\n" +
	"\x19prolongation_comment_html\x18\x1f \x01(\tR\x17prolongationCommentHtml\x12A\n" +
	"\x1dhas_prolongation_comment_html\x18  \x01(\bR\x1ahasProlongationCommentHtml\x12@\n" +
	"\x1dis_in_office_opening_possible\x18! \x01(\bR\x19isInOfficeOpeningPossible\x12/\n" +
	"\x13detailed_conditions\x18\" \x01(\tR\x12detailedConditions\x126\n" +
	"\x17has_detailed_conditions\x18# \x01(\bR\x15hasDetailedConditions\x129\n" +
	"\x19is_rate_increase_possible\x18$ \x01(\bR\x16isRateIncreasePossible\x12/\n" +
	"\x13percent_calculation\x18% \x01(\tR\x12percentCalculation\x126\n" +
	"\x17has_percent_calculation\x18& \x01(\bR\x15hasPercentCalculation\x12\"\n" +
	"\ris_new_client\x18' \x01(\bR\visNewClient\x12,\n" +
	"\x12new_client_comment\x18( \x01(\tR\x10newClientComment\x123\n" +
	"\x16has_new_client_comment\x18) \x01(\bR\x13hasNewClientComment\x12 \n" +
	"\fis_new_money\x18* \x01(\bR\n" +
	"isNewMoney\x12*\n" +
	"\x11new_money_comment\x18+ \x01(\tR\x0fnewMoneyComment\x121\n" +
	"\x15has_new_money_comment\x18, \x01(\bR\x12hasNewMoneyComment\x12+\n" +
	"\x12is_key_rate_linked\x18- \x01(\bR\x0fisKeyRateLinked\x125\n" +
	"\x17key_rate_linked_comment\x18. \x01(\tR\x14keyRateLinkedComment\x12<\n" +
	"\x1bhas_key_rate_linked_comment\x18/ \x01(\bR\x17hasKeyRateLinkedComment\x12=\n" +
	"\x0erates_extremum\x180 \x01(\v2\x16.project.RatesExtremumR\rratesExtremum\x1a>\n" +
	"\x10FeatureListEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\x1aH\n" +
	"\x1aCapitalizationPeriodsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc3\x02\n" +
	"\rRatesExtremum\x12\x19\n" +
	"\bmin_rate\x18\x01 \x01(\x02R\aminRate\x12\x19\n" +
	"\bmax_rate\x18\x02 \x01(\x02R\amaxRate\x12\x1d\n" +
	"\n" +
	"min_amount\x18\x03 \x01(\x05R\tminAmount\x12\x1d\n" +
	"\n" +
	"max_amount\x18\x04 \x01(\x05R\tmaxAmount\x12$\n" +
	"\x0ehas_max_amount\x18\x05 \x01(\bR\fhasMaxAmount\x12\x1d\n" +
	"\n" +
	"min_period\x18\x06 \x01(\x05R\tminPeriod\x12\x1d\n" +
	"\n" +
	"max_period\x18\a \x01(\x05R\tmaxPeriod\x12$\n" +
	"\x0ehas_max_period\x18\b \x01(\bR\fhasMaxPeriod\x124\n" +
	"\vrates_table\x18\t \x03(\v2\x13.project.RatesTableR\n" +
	"ratesTable\"f\n" +
	"\n" +
	"RatesTable\x12\x12\n" +
	"\x04rate\x18\x01 \x01(\x02R\x04rate\x12#\n" +
	"\rfrom_notation\x18\x02 \x01(\tR\ffromNotation\x12\x1f\n" +
	"\vto_notation\x18\x03 \x01(\tR\n" +
	"toNotation\"\x80\a\n" +
	"\x04Bond\x12\x12\n" +
	"\x04isin\x18\x01 \x01(\tR\x04isin\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"name_short\x18\x03 \x01(\tR\tnameShort\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"list_level\x18\x05 \x01(\tR\tlistLevel\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"reg_number\x18\a \x01(\tR\tregNumber\x12\x1d\n" +
	"\n" +
	"issue_size\x18\b \x01(\x05R\tissueSize\x12\x1f\n" +
	"\vlist_volume\x18\t \x01(\x05R\n" +
	"listVolume\x12\x19\n" +
	"\bmin_step\x18\n" +
	" \x01(\x02R\aminStep\x12\x1a\n" +
	"\bdecimals\x18\v \x01(\tR\bdecimals\x12\x18\n" +
	"\aemitent\x18\f \x01(\tR\aemitent\x12\x19\n" +
	"\bmat_date\x18\r \x01(\tR\amatDate\x12,\n" +
	"\x12initial_face_value\x18\x0e \x01(\x02R\x10initialFaceValue\x12\x1d\n" +
	"\n" +
	"face_value\x18\x0f \x01(\x02R\tfaceValue\x12*\n" +
	"\x11yield_to_maturity\x18\x10 \x01(\x02R\x0fyieldToMaturity\x121\n" +
	"\x15has_yield_to_maturity\x18\x11 \x01(\bR\x12hasYieldToMaturity\x12#\n" +
	"\rcoupon_period\x18\x12 \x01(\x05R\fcouponPeriod\x12%\n" +
	"\x0ecoupon_percent\x18\x13 \x01(\x02R\rcouponPercent\x12!\n" +
	"\fcoupon_value\x18\x14 \x01(\x02R\vcouponValue\x12\x1f\n" +
	"\vaccrued_int\x18\x15 \x01(\x02R\n" +
	"accruedInt\x12\x1a\n" +
	"\bcurrency\x18\x16 \x01(\tR\bcurrency\x12#\n" +
	"\remitent_title\x18\x17 \x01(\tR\femitentTitle\x12\x1f\n" +
	"\vemitent_inn\x18\x18 \x01(\tR\n" +
	"emitentInn\x12\x19\n" +
	"\bboard_id\x18\x19 \x01(\tR\aboardId\x12\x14\n" +
	"\x05secid\x18\x1a \x01(\tR\x05secid\x12\x1d\n" +
	"\n" +
	"short_name\x18\x1b \x01(\tR\tshortName\x12\x12\n" +
	"\x04last\x18\x1c \x01(\x02R\x04last\x12\x19\n" +
	"\bhas_last\x18\x1d \x01(\bR\ahasLast2\xa8\x03\n" +
	"\x0eProjectService\x12?\n" +
	"\bGetStats\x12\x18.project.GetStatsRequest\x1a\x19.project.GetStatsResponse\x126\n" +
	"\x05Fetch\x12\x15.project.FetchRequest\x1a\x16.project.FetchResponse\x12Q\n" +
	"\x0eGetAllDeposits\x12\x1e.project.GetAllDepositsRequest\x1a\x1f.project.GetAllDepositsResponse\x12Q\n" +
	"\x0eGetDepositByID\x12\x1e.project.GetDepositByIDRequest\x1a\x1f.project.GetDepositByIDResponse\x12?\n" +
	"\bGetBonds\x12\x18.project.GetBondsRequest\x1a\x19.project.GetBondsResponse\x126\n" +
	"\x05Query\x12\x15.project.QueryRequest\x1a\x16.project.QueryResponseB\x1dZ\x1bbackend/internal/grpc/pb;pbb\x06proto3"

var (
	file_proto_project_proto_rawDescOnce sync.Once
	file_proto_project_proto_rawDescData []byte
)

func file_proto_project_proto_rawDescGZIP() []byte {
	file_proto_project_proto_rawDescOnce.Do(func() {
		file_proto_project_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_project_proto_rawDesc), len(file_proto_project_proto_rawDesc)))
	})
	return file_proto_project_proto_rawDescData
}

var file_proto_project_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_proto_project_proto_goTypes = []any{
	(*GetStatsRequest)(nil),        // 0: project.GetStatsRequest
	(*GetStatsResponse)(nil),       // 1: project.GetStatsResponse
	(*CategoryStat)(nil),           // 2: project.CategoryStat
	(*FetchRequest)(nil),           // 3: project.FetchRequest
	(*FetchResponse)(nil),          // 4: project.FetchResponse
	(*GetAllDepositsRequest)(nil),  // 5: project.GetAllDepositsRequest
	(*GetAllDepositsResponse)(nil), // 6: project.GetAllDepositsResponse
	(*GetDepositByIDRequest)(nil),  // 7: project.GetDepositByIDRequest
	(*GetDepositByIDResponse)(nil), // 8: project.GetDepositByIDResponse
	(*GetBondsRequest)(nil),        // 9: project.GetBondsRequest
	(*GetBondsResponse)(nil),       // 10: project.GetBondsResponse
	(*QueryRequest)(nil),           // 11: project.QueryRequest
	(*QueryResponse)(nil),          // 12: project.QueryResponse
	(*ProductList)(nil),            // 13: project.ProductList
	(*ProductResult)(nil),          // 14: project.ProductResult
	(*Deposit)(nil),                // 15: project.Deposit
	(*RatesExtremum)(nil),          // 16: project.RatesExtremum
	(*RatesTable)(nil),             // 17: project.RatesTable
	(*Bond)(nil),                   // 18: project.Bond
	nil,                            // 19: project.QueryResponse.ResultsEntry
	nil,                            // 20: project.Deposit.FeatureListEntry
	nil,                            // 21: project.Deposit.CapitalizationPeriodsEntry
}
var file_proto_project_proto_depIdxs = []int32{
	2,  // 0: project.GetStatsResponse.stats:type_name -> project.CategoryStat
	15, // 1: project.GetAllDepositsResponse.deposits:type_name -> project.Deposit
	15, // 2: project.GetDepositByIDResponse.deposit:type_name -> project.Deposit
	18, // 3: project.GetBondsResponse.bonds:type_name -> project.Bond
	19, // 4: project.QueryResponse.results:type_name -> project.QueryResponse.ResultsEntry
	14, // 5: project.ProductList.products:type_name -> project.ProductResult
	20, // 6: project.Deposit.feature_list:type_name -> project.Deposit.FeatureListEntry
	21, // 7: project.Deposit.capitalization_periods:type_name -> project.Deposit.CapitalizationPeriodsEntry
	16, // 8: project.Deposit.rates_extremum:type_name -> project.RatesExtremum
	17, // 9: project.RatesExtremum.rates_table:type_name -> project.RatesTable
	13, // 10: project.QueryResponse.ResultsEntry.value:type_name -> project.ProductList
	0,  // 11: project.ProjectService.GetStats:input_type -> project.GetStatsRequest
	3,  // 12: project.ProjectService.Fetch:input_type -> project.FetchRequest
	5,  // 13: project.ProjectService.GetAllDeposits:input_type -> project.GetAllDepositsRequest
	7,  // 14: project.ProjectService.GetDepositByID:input_type -> project.GetDepositByIDRequest
	9,  // 15: project.ProjectService.GetBonds:input_type -> project.GetBondsRequest
	11, // 16: project.ProjectService.Query:input_type -> project.QueryRequest
	1,  // 17: project.ProjectService.GetStats:output_type -> project.GetStatsResponse
	4,  // 18: project.ProjectService.Fetch:output_type -> project.FetchResponse
	6,  // 19: project.ProjectService.GetAllDeposits:output_type -> project.GetAllDepositsResponse
	8,  // 20: project.ProjectService.GetDepositByID:output_type -> project.GetDepositByIDResponse
	10, // 21: project.ProjectService.GetBonds:output_type -> project.GetBondsResponse
	12, // 22: project.ProjectService.Query:output_type -> project.QueryResponse
	17, // [17:23] is the sub-list for method output_type
	11, // [11:17] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_project_proto_init() }
func file_proto_project_proto_init() {
	if File_proto_project_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_project_proto_rawDesc), len(file_proto_project_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_project_proto_goTypes,
		DependencyIndexes: file_proto_project_proto_depIdxs,
		MessageInfos:      file_proto_project_proto_msgTypes,
	}.Build()
	File_proto_project_proto = out.File
	file_proto_project_proto_goTypes = nil
	file_proto_project_proto_depIdxs = nil
}
